---
title: Ilan's Bloggo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: This is Ilan's home.
logo: favicon.png
url: ilansbloggo.manumasson.com
image: assets/images/bg.jpg
rss_url: "/feed.xml"
permalink: "/blog/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: assets/_sass
  style: compressed
email: ilan354@gmail.com
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
facebook: IlanMasson
github: IlanMasson
stackoverflow: 6438519/Ilan-Masson
linkedin: MassonIlan
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
exclude:
- README.md
- Gemfile
- Gemfile.lock
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
- ".sass-cache"
- ".DS_Store"
- ".idea"
